version: '3.7'

services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile # Create a Dockerfile for your NestJS app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production

  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    ports:
      - '3001:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus